---
title: qfBlog
author:
  name: "qf blog"

safe: true
#source: 'git@github.com:johnkstockton/qfblog.git'
lsi: false


server: false
server_port: 4000
base-url: /
production_url: "http://blog.quantifind.com"

source: .
author_dir: 'author'
destination: ./_site
plugins: ./_plugins
exclude:
  - README.md
  - util
  - drafts
  - config
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - vendor
  - config.ru
  - unicorn.rb
  - fabfile.py

photos:
  - 'blog-image-01.jpg'
  - 'blog-image-02.jpg'
  - 'blog-image-03.jpg'

future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: "/posts/:title"

tag_page_layout: tag_page
tag_page_dir: tag

rdiscount:
  extensions:
    - smart

